name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build 
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install dependencies
        run: npm install

      - name: Build 
        run: npm run build

      - name: Archive build files
        run: tar -czvf dist.tar.gz dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist.tar.gz


#   deploy:
#     name: Deploy to Server
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#       - name: Download build artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: angular-build
#           path: .

#       - name: Copy artifact to server
#         run: |
#           scp -o StrictHostKeyChecking=no app.zip ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/tmp/app.zip
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Deploy on server
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#           unzip -o /tmp/app.zip -d /var/www/html
#           rm /tmp/app.zip
#           sudo systemctl restart nginx
#           EOF
